exceptions_arr = {
    'ValueError': 'Введены данные некорректного типа',
    'WrongLimitsArgument': 'Введенные данные не соответсвуют ни одному пункту',
}